name: Scrape latest data

on:
  push:
    branches:    
      - main
  schedule:
    - cron:  '7 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        repo:
          - kubernetes/kops
          - kubernetes/kubernetes
          - hashicorp/terraform
          - terraform-providers/terraform-provider-aws
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Fetch latest data
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |-
        go run main.go ${{ matrix.repo }}
    - name: Commit and push if it changed
      run: |-
        git config user.name "github bot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Data update ${{ matrix.repo }}: ${timestamp}" || exit 0
        git push
